# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x03\x61ux*\x1e\n\x08Platform\x12\x07\n\x03IOS\x10\x01\x12\t\n\x05\x44ROID\x10\x02*)\n\x10\x44\x65viceFormFactor\x12\t\n\x05PHONE\x10\x01\x12\n\n\x06TABLET\x10\x02*k\n\tAdNetwork\x12\n\n\x06VUNGLE\x10\x00\x12\x0e\n\nCHARTBOOST\x10\x01\x12\r\n\tAD_COLONY\x10\x02\x12\x0c\n\x08HYPER_MX\x10\x03\x12\t\n\x05UNITY\x10\x04\x12\x0c\n\x08\x46\x41\x43\x45\x42OOK\x10\x05\x12\x0c\n\x08\x41PPLOVIN\x10\x06')

_PLATFORM = DESCRIPTOR.enum_types_by_name['Platform']
Platform = enum_type_wrapper.EnumTypeWrapper(_PLATFORM)
_DEVICEFORMFACTOR = DESCRIPTOR.enum_types_by_name['DeviceFormFactor']
DeviceFormFactor = enum_type_wrapper.EnumTypeWrapper(_DEVICEFORMFACTOR)
_ADNETWORK = DESCRIPTOR.enum_types_by_name['AdNetwork']
AdNetwork = enum_type_wrapper.EnumTypeWrapper(_ADNETWORK)
IOS = 1
DROID = 2
PHONE = 1
TABLET = 2
VUNGLE = 0
CHARTBOOST = 1
AD_COLONY = 2
HYPER_MX = 3
UNITY = 4
FACEBOOK = 5
APPLOVIN = 6


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLATFORM._serialized_start=21
  _PLATFORM._serialized_end=51
  _DEVICEFORMFACTOR._serialized_start=53
  _DEVICEFORMFACTOR._serialized_end=94
  _ADNETWORK._serialized_start=96
  _ADNETWORK._serialized_end=203
# @@protoc_insertion_point(module_scope)
